### ISSUE TITLE
hello HDMI

### ISSUE THREAD

**Issue by cyb3rx7** [felixyonathan/Asus-TUF-FX504GE-OpenCore#1]
Hello bro HDMI work with u ?

**Comment by felixyonathan** [comment]
haven't tried yet as I don't really use it on MacOS. I will test it and let you know later.

**Comment by cyb3rx7** [comment]
okay bro thx

**Comment by felixyonathan** [comment]
@cyb3rx7n It's not working. Got any suggestion or anything I can help? Btw I'm going to do it from scratch (updating to 0.6.1 anyway so yeah, why not).

**Comment by cyb3rx7** [comment]
i did some serching any way if u on 10.15.4 and up will not working 
2 maybe we have to set hdmi work on cpu nopt on nvidia gpu 
but the hdmi is connect to nvidia card so 
u have to retry to push some disable and enable for hdmi pro 
3 if u have windows maybe becuse u have drive nvidia will not work i did all but yasterday i just downgrade to 10.14.6 and i will try again soon and see if any think ill working 
my old system was catalina 10.15.6 i did almost every thing i found it but not owkring with me try and tell me bro thx any way

**Comment by felixyonathan** [comment]
AFAIK the HDMI is always connected the CPU on Optimus laptops (mine, yours (?)). I did disable NVIDIA GPU (required on Optimus laptops). I didn't bother with it too much because I don't use it. I'll try to get it working when updating to OC 0.6.1. Thank you for the discussion bro.

**Comment by cyb3rx7** [comment]
no if u look in windows u will see it's connect to nvidia card

**Comment by felixyonathan** [comment]
yeah you're right... Sorry I forgot (I am actually aware of the fact). as I didn't use HDMI on MacOS. For Optimus laptops, there will be no way to connect to the HDMI, as you've to write the driver handling GPU switch (no one's doing that). May as well just buy a PC or a laptop without Optimus (for this/my case, a laptop with only NVIDIA GPU and no Intel GPU).

**Comment by cyb3rx7** [comment]
hi there i see some say there use displaylink drive with cable usb to hdmi and work with them but i can't found it soon becuse that i look up for way to try before i buy it thanks any way

**Comment by cyb3rx7** [comment]
if u look here u lill see it's use usb to hdmi displaylink 

https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh
